### PR TITLE
DGCNN Inserted missing .contiguous() call

### PR DESCRIPTION
**Pull request by chrispduck**
This change was noted on the original implemented repo: [WangYueFt/dgcnn@98b744a](98b744a)

### CODE REVIEW

**Comment by krrish94** [comment]
@chrispduck Thanks for the quick PR!

It seems like you haven't signed off on your commit yet? Could you resolve this, for us to be able to merge? (see [this](https://github.com/NVIDIAGameWorks/kaolin/pull/245/checks?check_run_id=644167958) for a resolution)

**Comment by krrish94** [comment]
@chrispduck Could you please sign the commit, as our CONTRIBUTING guide requires?

I wouldn't be able to merge it in otherwise

**Review by krrish94 — CHANGES_REQUESTED** [review]
Commit needs to be signed off on. LGTM otherwise

**Comment by Caenorst** [comment]
@chrispduck commits needs with `-s` or `--signoff` not `-S`.
Fortunately you just have one commit => 
```
git commit --amend -s
git push --force origin master
```

will do the job.

Thanks for your contribution :)

**Comment by chrispduck** [comment]
@Caenorst Thanks for that. 

Happy to contribute!

**Comment by chrispduck** [comment]
Any ideas as to why this isn’t passing the build?

**Comment by Caenorst** [comment]
That is a weird error, maybe a CI temporarily problem, can you rebase with master and force push ?

**Comment by pushkalkatara** [comment]
Facing the same issue @Caenorst in the PR https://github.com/NVIDIAGameWorks/kaolin/pull/255

**Pull request closed without merging**
