### PR TITLE
windows fixes

### PR DESCRIPTION
**Pull request by jasongorski**
- fix a preprocessor operator
- fix sdfconversions test failure on windows
- also fix a str escape warning from pytests

Related issues:
#275 
#140 
#139 
#135 
#91 
#44 
#20 
#19 
#12 

Signed-off-by: Jason Gorski <jasongorski@users.noreply.github.com>

### CODE REVIEW

**Comment by Jean-Francois-Lafleche** [comment]
Changes look good! Setup was flawless on my system. Just a few items:

1. Please rebase to master - a fix was applied to setup.py that will let it pass the CI test.
2. Please create a `setenv.bat` version of `setenv.sh` and update the README accordingly.

**Comment by jasongorski** [comment]
@Jean-Francois-Lafleche, rebased, updated README.md (with additional note that USD support is unimplemented at this time, so no need for setenv.bat)

**Review by Jean-Francois-Lafleche — APPROVED** [review]
LGTM!

**Comment by MBrandt-NASA** [comment]
I'd recommend also including in the Windows instructions, either immediately before or after the vcvars64.bat command, the following:

set DISTUTILS_USE_SDK=1

I've had to do that each time.  Yes it's in the output as a suggestion when you try to run "python setup.py" but it would save dealing with the error to explicitly mention that in the Windows instructions.

**Comment by MBrandt-NASA** [comment]
I worked on the beginning of a setenv.bat for Windows.  It got the pytest errors down to 23... so still some issue with setting library paths I think since I still see errors like:

`(kaolin) λ pytest kaolin\tests\
=================================================== test session starts ==================================================== platform win32 -- Python 3.7.4, pytest-5.2.1, py-1.9.0, pluggy-0.13.1
rootdir: D:\AI\NVidia\kaolin
plugins: arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, remotedata-0.3.2
collected 36 items / 23 errors / 1 skipped / 12 selected

========================================================== ERRORS ========================================================== __________________________________ ERROR collecting tests/test_compute_adjacency_info.py ___________________________________ ImportError while importing test module 'D:\AI\NVidia\kaolin\tests\test_compute_adjacency_info.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
kaolin\tests\test_compute_adjacency_info.py:19: in <module>
    from kaolin.rep import TriangleMesh
E   ModuleNotFoundError: No module named 'kaolin.rep'`

But at least it some progress... 

Partial setenv.bat:

`:: Assign all Path variables
SET KAOLIN_HOME="D:\AI\NVidia\kaolin"

SET PYTHONPATH=.;"C:\Users\mabrandt\AppData\Local\Continuum\anaconda3\envs\kaolin";"C:\Users\[INSERT_USERNAME]\AppData\Local\Continuum\anaconda3\envs\kaolin\Lib\site-packages"

SET PATH=%PATH%;%PYTHONPATH%;"C:\Users\[INSERT_USERNAME]\AppData\Local\Continuum\anaconda3\envs\kaolin\Lib\site-packages"`

Kaolin imports in Python properly for me in Windows 10... just have some issues with the pytests.

**Comment by MBrandt-NASA** [comment]
Another crucial fix for Windows 10 -- in order to get Matplotlib plots to display from Pycharm properly, in:

kaolin\datasets\__init__.py

I had to comment out:

`#matplotlib.use('Agg')`

**Pull request merged**
